version: '3.9'

services:
  app:
    image: 'sha256:490aa39566296af4d8770c88ff698b7f527a975d8f4d3de628eab583fbb6f8de'
    container_name: app
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=5409
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5409
